name: Build & Push Odoo

on:
  push:
    branches: [ "18.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: odoo_production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: |
          echo "IMAGE=mydockerhubuser/odoo18" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "TAG_BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:latest
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_SHA }}
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_BRANCH }}
